apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickvisual.fullname" . }}
  labels:
    {{- include "clickvisual.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: server
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: server
    - name: governor
      port: 19011
      protocol: TCP
      targetPort: governor
  selector:
    {{- include "clickvisual.selectorLabels" . | nindent 4 }}
