image:
  registry: clickhouse/clickhouse-server:22.8.16.32
clickhouse:
  zookeeper:
    host: zk-client-clickhouse
    port: 2181
    identity: acos:acos2022
  clusters:
    name: dtstack
  user:
    password: "abc123"
resources:
  low:
    shardsCount: 1
    replicas: 1
    defaultStorageResourceRequest: "500Gi"
    resource:
      limits:
        cpu: 1000m
        memory: 2048Mi
      requests:
        cpu: 1000m
        memory: 2048Mi
  high:
    shardsCount: 2
    replicas: 2
    defaultStorageResourceRequest: "1000Gi"
    resource:
      limits:
        cpu: 6000m
        memory: 12288M
      requests:
        cpu: 6000m
        memory: 12288M


# zookeeper configuration
zookeeper:

  # configuration for zookeeper instance
  image: sealos.hub:5000/acos/zookeeper:3.6.2
  imagePullPolicy: Always
  imagePullSecrets: "" # 拉取镜像所需secret

  resources:
    low:
      replicas: 1
      defaultStorageResourceRequest: '50Gi'
      resource:
        limits:
          cpu: 1000m
          memory: 2048Mi
        requests:
          cpu: 1000m
          memory: 2048Mi
    high:
      replicas: 3
      defaultStorageResourceRequest: '500Gi'
      resource:
        limits:
          cpu: 4000m
          memory: 8192Mi
        requests:
          cpu: 2000m
          memory: 4096Mi

