image:
  registry: registry.cn-hangzhou.aliyuncs.com/openobservx/clickhouse-server:22.8.16.32

clickhouse:
  zookeeper:
    host: zk-client-clickhouse
    port: 2181
    identity: openobservx:openobservx
  clusters:
    name: openobservx
  user:
    password: "OpenObservX"
resources:
  shardsCount: 1
  replicas: 2
  defaultStorageResourceRequest: "100Gi"
  storageClass: ""
  resource:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 2048Mi
# zookeeper configuration
zookeeper:
  # configuration for zookeeper instance
  image: registry.cn-hangzhou.aliyuncs.com/openobservx/zookeeper:3.6.2
  imagePullPolicy: IfNotPresent
  imagePullSecrets: "" # 拉取镜像所需secret

  resources:
    replicas: 1
    defaultStorageResourceRequest: "50Gi"
    storageClass: ""
    resource:
      limits:
        cpu: 500m
        memory: 1024Mi
      requests:
        cpu: 500m
        memory: 1024Mi
