apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: "clickhouse-cluster"
spec:
  defaults:
    templates:
      podTemplate: clickhouse
      volumeClaimTemplate: ck-data-dir
      serviceTemplate: clickhouse-clickhouse-cluster
  configuration:
    zookeeper:
      nodes:
        - host: {{ .Values.clickhouse.zookeeper.host }}
          port: {{ .Values.clickhouse.zookeeper.port }}
      identity: {{ .Values.clickhouse.zookeeper.identity }}
    clusters:
      - name: "{{ .Values.clickhouse.clusters.name}}"
        secret:
          value: {{ .Values.clickhouse.user.password }}
        layout:
          shardsCount: {{ (index .Values.resources .Values.global.resourceProfile).shardsCount }}
          replicasCount: {{ (index .Values.resources .Values.global.resourceProfile).replicas }}
    users:
      default/password: {{ .Values.clickhouse.user.password }}
      default/networks/ip: "::/0"
  templates:
    podTemplates:
      - name: clickhouse
        metadata:
          labels:
            app: clickhouse
          annotations:
            prometheus.io/scrape: 'true'
            prometheus.io/tcp-probe: 'true'
            prometheus.io/tcp-probe-port: '8123,9000'
        spec:
          containers:
          - name: clickhouse-cluster
            image: {{ .Values.global.acos.imagePrefix }}/clickhouse-server:21.12.3.32
            volumeMounts:
            - mountPath: /etc/clickhouse-server/config.xml
              name: chi-clickhouse-cluster-config-file
              subPath: config.xml
            resources:
              {{- toYaml (index $.Values.resources $.Values.global.resourceProfile).resource | nindent 14 }}
          volumes:
          - configMap:
              name: chi-clickhouse-cluster-config-file
            name: chi-clickhouse-cluster-config-file
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - "clickhouse"
                  topologyKey: kubernetes.io/hostname
    volumeClaimTemplates:
      - name: ck-data-dir
        spec:
          storageClassName: {{ .Values.global.acos.storageClass }}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ (index $.Values.resources $.Values.global.resourceProfile).defaultStorageResourceRequest }}
    serviceTemplates:
      - name: clickhouse-clickhouse-cluster
        generateName: "clickhouse-cluster"
        spec:
          ports:
            - name: native
              port: 9000
              targetPort: 9000
            - name: http
              port: 8123
              targetPort: 8123
            - name: prometheus
              port: 8001
              targetPort: 8001
          type: ClusterIP
