{{- $replicasValue := .Values.zookeeper.resources }}
{{- $replicasInt := int $replicasValue.replicas }}


{{- range $i := until $replicasInt }}
apiVersion: v1
kind: Service
metadata:
  # DNS would be like zookeeper.zoons
  name: zk-clickhouse-{{ $i }}
  labels:
    app: zk-clickhouse
spec:
  clusterIP: None
  ports:
    - port: 2181
      name: client
  selector:
    app: zk-clickhouse
    what: node
    statefulset.kubernetes.io/pod-name: zk-clickhouse-{{ $i }}
{{- end }}

