# Template Parameters:
#
# NAME=etc-clickhouse-operator-files
# NAMESPACE=kube-system
# COMMENT=
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-files" (include "clickhouse-operator.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "clickhouse-operator.labels" . | nindent 4 }}
data: {{ tpl (toYaml .Values.configs.files) . | nindent 2 }}
