{{- if .Values.serviceAccount.create -}}
# Template Parameters:
#
# COMMENT=
# NAMESPACE=kube-system
# NAME=clickhouse-operator
#
# Setup ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clickhouse-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "clickhouse-operator.labels" . | nindent 4 }}
  annotations: {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end -}}
